<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

subsetting - selecting from a set to make another set

indexing - selecting specific elements from list

slicing - selectin a range of elements

masking - hiding some elements that you dont want to see

In [3]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers = np_array_2d[:,0]

numbers_int = numbers.astype(int)

mask_even = numbers_int % 2 != 0

alphabets = np_array_2d[mask_even,1]

print (alphabets)

['A' 'C' 'E' 'G' 'I']


In [21]:
import numpy as np


matrix = np.array([[66, 50, 57, -1, -1],[92, -1, 88, -1, -1],[75, -1, -1, 76, -1], [-1, 51, 87, -1, -1],[71, -1, 67, -1, 69]])

mask_under_50 = matrix < 50

mask_over_50 = matrix >50

mask_equal_50 = matrix == 50

matrix[mask_under_50] = -1
matrix[mask_over_50] = 1
matrix[mask_equal_50] = 0

print(matrix)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
